# Generated by Django 4.1 on 2022-08-15 08:14

import apps.migrate_csv.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.migrate_csv.models.file_upload_to, verbose_name='Csv file')),
                ('migrated_in_preview_table', models.BooleanField(default=False)),
                ('migrated_in_production', models.BooleanField(default=False)),
                ('migrated_at', models.DateTimeField(blank=True, null=True, verbose_name='Migrated at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Assigned at')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_csv_files', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_csv_files', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('migrated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_by', to=settings.AUTH_USER_MODEL, verbose_name='Migrated by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_csv_files', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
        ),
        migrations.CreateModel(
            name='CsvFilePreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbreak', models.CharField(blank=True, max_length=255, verbose_name='Outbreak')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Country')),
                ('iso3', models.CharField(blank=True, max_length=255, verbose_name='ISO3')),
                ('adminlevel1', models.CharField(blank=True, max_length=255, verbose_name='Admin Level 1')),
                ('indicator', models.CharField(blank=True, max_length=255, verbose_name='Indicator')),
                ('indicator_id', models.CharField(blank=True, max_length=255, verbose_name='Indicator id')),
                ('dimension', models.CharField(blank=True, max_length=255, verbose_name='Dimension')),
                ('questions', models.CharField(blank=True, max_length=255, verbose_name='Questions')),
                ('percentage', models.CharField(blank=True, max_length=255, verbose_name='Percentage')),
                ('nominator', models.IntegerField(blank=True, verbose_name='Nominator')),
                ('denominator', models.IntegerField(blank=True, verbose_name='Denominator')),
                ('gender', models.CharField(blank=True, max_length=255, verbose_name='Gender')),
                ('age_group', models.CharField(blank=True, max_length=255, verbose_name='Age group')),
                ('age_info', models.CharField(blank=True, max_length=255, verbose_name='Age info')),
                ('target_group', models.CharField(blank=True, max_length=255, verbose_name='Target group')),
                ('date', models.DateField(blank=True, verbose_name='Date')),
                ('contribution_marker', models.CharField(blank=True, max_length=255, verbose_name='Contribution marker')),
                ('errormargin', models.CharField(blank=True, max_length=255, verbose_name='Error margin')),
                ('representativeness', models.CharField(blank=True, max_length=255, verbose_name='Representativeness')),
                ('area', models.CharField(blank=True, max_length=255, verbose_name='Area')),
                ('limitation', models.CharField(blank=True, max_length=255, verbose_name='Limitation')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Comment')),
                ('source_id', models.CharField(blank=True, max_length=255, verbose_name='Source id')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Topic')),
                ('thematic', models.CharField(blank=True, max_length=255, verbose_name='Thematic')),
                ('subindicator', models.CharField(blank=True, max_length=255, verbose_name='Sub indicator')),
                ('is_outlier', models.BooleanField(default=False)),
                ('outlier_remarks', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, verbose_name='Reviewed at')),
                ('csv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_file_previews', to='migrate_csv.csvfile', verbose_name='Csv file form')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_csv_previews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
        ),
    ]
