# Generated by Django 4.1 on 2022-09-01 05:43

import apps.migrate_csv.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.migrate_csv.models.file_upload_to, verbose_name='CSV file')),
                ('file_type', models.SmallIntegerField(choices=[(0, 'RCCE Data Input User'), (1, 'RCCE Data Input User Sources')])),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Processing (Extraction + Outlier Detection)'), (2, 'Preview'), (3, 'Migrated'), (4, 'Canceled'), (500, 'Failed Processing'), (501, 'Failed Migrating')], default=0)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Assigned at')),
                ('migrated_at', models.DateTimeField(blank=True, null=True, verbose_name='Migrated at')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('migrated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Migrated by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
        ),
        migrations.CreateModel(
            name='ImportUserSourceDataPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed at')),
                ('is_outlier', models.BooleanField(default=False)),
                ('outlier_data', models.JSONField(blank=True, default=list)),
                ('source_id', models.CharField(blank=True, max_length=255, verbose_name='Source ID')),
                ('organisation', models.CharField(blank=True, max_length=255, verbose_name='Organisation')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('authors', models.CharField(blank=True, max_length=255, verbose_name='Authors')),
                ('sample_type', models.CharField(blank=True, max_length=255, verbose_name='Sample type')),
                ('survey_method', models.CharField(blank=True, max_length=255, verbose_name='Survey Method')),
                ('sample', models.IntegerField(blank=True, verbose_name='Sample')),
                ('targetpop', models.CharField(blank=True, max_length=255, verbose_name='TargetPop')),
                ('scale', models.CharField(blank=True, max_length=255, verbose_name='Scale')),
                ('quality_check', models.CharField(blank=True, max_length=255, verbose_name='Quality Check')),
                ('data_access_type', models.CharField(blank=True, max_length=255, verbose_name='Data Access Type')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Comment')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='Source')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Link')),
                ('source_date', models.DateField(blank=True, verbose_name='Source Date')),
                ('key_words', models.CharField(blank=True, max_length=255, verbose_name='Key Words')),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_previews', to='migrate_csv.dataimport', verbose_name='Csv file form')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportUserDataPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed at')),
                ('is_outlier', models.BooleanField(default=False)),
                ('outlier_data', models.JSONField(blank=True, default=list)),
                ('source_id', models.CharField(blank=True, max_length=255, verbose_name='Source id')),
                ('outbreak', models.CharField(blank=True, max_length=255, verbose_name='Outbreak')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Country')),
                ('iso3', models.CharField(blank=True, max_length=255, verbose_name='ISO3')),
                ('adminlevel1', models.CharField(blank=True, max_length=255, verbose_name='Admin Level 1')),
                ('indicator', models.CharField(blank=True, max_length=255, verbose_name='Indicator')),
                ('indicator_id', models.CharField(blank=True, max_length=255, verbose_name='Indicator id')),
                ('dimension', models.CharField(blank=True, max_length=255, verbose_name='Dimension')),
                ('questions', models.CharField(blank=True, max_length=255, verbose_name='Questions')),
                ('percentage', models.FloatField(blank=True, verbose_name='Percentage')),
                ('nominator', models.IntegerField(blank=True, verbose_name='Nominator')),
                ('denominator', models.IntegerField(blank=True, verbose_name='Denominator')),
                ('errormargin', models.FloatField(blank=True, verbose_name='Error margin')),
                ('limitation', models.IntegerField(blank=True, verbose_name='Limitation')),
                ('gender', models.CharField(blank=True, max_length=255, verbose_name='Gender')),
                ('age_group', models.CharField(blank=True, max_length=255, verbose_name='Age group')),
                ('age_info', models.CharField(blank=True, max_length=255, verbose_name='Age info')),
                ('target_group', models.CharField(blank=True, max_length=255, verbose_name='Target group')),
                ('date', models.DateField(blank=True, verbose_name='Date')),
                ('contribution_marker', models.CharField(blank=True, max_length=255, verbose_name='Contribution marker')),
                ('representativeness', models.CharField(blank=True, max_length=255, verbose_name='Representativeness')),
                ('area', models.CharField(blank=True, max_length=255, verbose_name='Area')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Comment')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Topic')),
                ('thematic', models.CharField(blank=True, max_length=255, verbose_name='Thematic')),
                ('subindicator', models.CharField(blank=True, max_length=255, verbose_name='Sub indicator')),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_previews', to='migrate_csv.dataimport', verbose_name='Csv file form')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
