# Generated by Django 4.1 on 2022-08-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrate_csv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='file_type',
            field=models.CharField(choices=[('main', 'Main'), ('supplementary', 'Supplementary')], default='main', max_length=20),
        ),
    ]
