# Generated by Django 4.1.1 on 2022-09-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrate_csv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importuserdatapreview',
            name='is_outlier',
        ),
        migrations.RemoveField(
            model_name='importusersourcedatapreview',
            name='is_outlier',
        ),
        migrations.AddField(
            model_name='importuserdatapreview',
            name='no_outlier',
            field=models.BooleanField(default=False, verbose_name='No outlier'),
        ),
        migrations.AddField(
            model_name='importusersourcedatapreview',
            name='no_outlier',
            field=models.BooleanField(default=False, verbose_name='No outlier'),
        ),
    ]
