# Generated by Django 4.1.1 on 2022-10-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrate_csv', '0002_remove_importuserdatapreview_is_outlier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryFilterOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso3', models.CharField(max_length=3)),
                ('emergency', models.CharField(max_length=50)),
                ('indicator_id', models.CharField(default='', max_length=50)),
                ('indicator_description', models.CharField(blank=True, max_length=250, null=True)),
                ('subvariable', models.CharField(max_length=255)),
            ],
        ),
    ]
