# Generated by Django 4.1.1 on 2022-11-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrate_csv', '0003_countryfilteroptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryfilteroptions',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
