# Generated by Django 4.1.1 on 2022-11-23 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrate_csv', '0004_countryfilteroptions_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountryFilterOptions',
            new_name='CachedCountryFilterOptions',
        ),
    ]
