# Generated by Django 4.1.1 on 2022-12-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrate_csv', '0006_alter_dataimport_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedcountryfilteroptions',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
