# Generated by Django 4.1.1 on 2023-01-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrate_csv', '0007_cachedcountryfilteroptions_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedcountryfilteroptions',
            name='thematic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cachedcountryfilteroptions',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
